version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=residentdb

  app:
    build:
      context: .
    container_name: visitor-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/residentdb
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
    env_file:
      - .env

volumes:
  mongo-data:
