version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    env_file:
      - .env
    restart: always

  app:
    build:
      context: .
    container_name: visitor-backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=8080
    env_file:
      - .env

volumes:
  mongo-data:
